<?php
/**
 * Integrations with the WordPress media library.
 *
 * Filters which catch the output of the media uploader or manager and convert
 * <img> tags to [img] shortcodes, so that they can be handled through
 * customizable templates.
 */

class Img_Shortcode_Integrations {

	/**
	 * Catch images inserted through the media library, and convert them to the
	 * shortcode format introduced by this plugin.
	 *
	 * @filter media_send_to_editor
	 * @param string $html Generated by `wp_ajax_send_attachment_to_editor()`
	 * @param int $id Attachment ID
	 * @param array $attachment Attributes selected in the media editor
	 * @return string
	 */
	public static function filter_media_send_to_editor( $html, $attachment_id, $attachment ) {

		$shortcode_attrs = array();

		$shortcode = '[img ';

		if ( $attachment_id = intval( $attachment_id ) ) {
			$shortcode .= 'attachment=' . $attachment_id . ' ';
		}

		$allowed_attrs = array(
			'size' => 'size',
			'align' => 'align',
			'image_alt' => 'alt',
		);

		foreach ( $allowed_attrs as $attachment_attr => $shortcode_attr ) {
			if ( ! empty( $attachment[ $attachment_attr ] ) ) {
				$shortcode .= sanitize_key( $shortcode_attr ) . '="' . esc_attr( $attachment[ $attachment_attr ] ) . '" ';
			}
		}

		$shortcode .= '/]';

		return preg_replace( '/<img[^>]*>/', $shortcode, $html );
	}

}

